### ISSUE TITLE
AttributeError for extract_django_settings_module when combined with newest django-stubs

### ISSUE THREAD

**Issue by henribru** [typeddjango/djangorestframework-stubs#202]
# Bug report

## What's wrong
When combining djangorestframework-stubs 1.4 with the newly released django-stubs 1.10.0, Mypy will fail with:
```
Error constructing plugin instance of NewSemanalDRFPlugin

Traceback (most recent call last):
  File "/home/henribru/.cache/pypoetry/virtualenvs/lightkeeper-nCOOTSLY-py3.10/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/henribru/.cache/pypoetry/virtualenvs/lightkeeper-nCOOTSLY-py3.10/lib/python3.10/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 96, in main
  File "mypy/main.py", line 173, in run_build
  File "mypy/build.py", line 180, in build
  File "mypy/build.py", line 231, in _build
  File "mypy/build.py", line 478, in load_plugins
  File "mypy/build.py", line 456, in load_plugins_from_config
  File "/home/henribru/.cache/pypoetry/virtualenvs/lightkeeper-nCOOTSLY-py3.10/lib/python3.10/site-packages/mypy_drf_plugin/main.py", line 25, in __init__
    django_settings_module = mypy_django_main.extract_django_settings_module(options.config_file)
AttributeError: module 'mypy_django_plugin.main' has no attribute 'extract_django_settings_module'
```

This is happening because `extract_django_settings_module` was removed in https://github.com/typeddjango/django-stubs/commit/edec5a1c99a784208d5d8ce78237016cdaa1c54f

## How is that should be
Ideally it should work with the newest django-stubs

## System information

- OS:
- `python` version: 3.10
- `django` version: 3.2.12
- `mypy` version: 0.941
- `django-stubs` version: 1.10.0

**Comment by sondrelg** [comment]
In case it unblocks anyone: I created a quick fix for myself [here](https://github.com/sondrelg/djangorestframework-stubs/commit/ca035c8a7d95b863f1474dd7f923877e433e66be). Think `configparser` might only work for mypy.ini setups though.

**Comment by psasselum** [comment]
Fixed by setting django-stubs to 1.9.0
